plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tymek.fireworks'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tymek.fireworks'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
